### ISSUE TITLE
Add songs to interface

### ISSUE THREAD

**Issue by eiroff** [eiroff/ultimossonetos#3]
1. Erik Satie - Gnossienne No.1 (index.html)
2. Erik Satie - Gnossienne No.3 (chapter*.html)
3. Implement play&pause function.

**Comment by ericcristhiano** [comment]
Developed.
Added audios as iframes to prevent autoplay policy from Google Chrome (https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

**Comment by eiroff** [comment]
First issue completed!
